version: "3.8"

services:
  qbittorrent:
    container_name: qbittorrent
    image: linuxserver/qbittorrent:latest
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Shanghai
      - WEBUI_PORT=8080
    volumes:
      - /mnt/media_rw/3d24fb66-314f-48b9-a26f-f91999170865/.ugreen_nas/155924/qbittorrent/config:/config
      - /mnt/mergerfs/mountpoint:/downloads
    network_mode: host
    depends_on:
      - mergerfs
    restart: always

  jellyfin:
    container_name: jellyfin
    image: linuxserver/jellyfin:latest
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Shanghai
      - DOCKER_MODS=linuxserver/mods:jellyfin-opencl-intel
    volumes:
      - /mnt/media_rw/3d24fb66-314f-48b9-a26f-f91999170865/.ugreen_nas/155924/jellyfin/config:/config
      - /mnt/media_rw/3d24fb66-314f-48b9-a26f-f91999170865/.ugreen_nas/155924/jellyfin/fonts:/usr/share/fonts
      - /mnt/mergerfs/mountpoint:/data
    network_mode: host
    depends_on:
      - clash-premium
      - mergerfs
    restart: always

  komga:
    container_name: komga
    image: gotson/komga:latest
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /mnt/media_rw/3d24fb66-314f-48b9-a26f-f91999170865/.ugreen_nas/155924/komga/config:/config
      - /mnt/media_rw/3d24fb66-314f-48b9-a26f-f91999170865/.ugreen_nas/155924/komga/tmp:/tmp
      - /mnt/mergerfs/mountpoint/Books:/data
    network_mode: host
    user: 0:0
    depends_on:
      - mergerfs
    restart: always

  homeassistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:latest
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /mnt/media_rw/3d24fb66-314f-48b9-a26f-f91999170865/.ugreen_nas/155924/homeassistant/config:/config
    privileged: true
    network_mode: host
    restart: always

  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: ["start.sh", "immich"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
      - mergerfs
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.yml
    #   service: hwaccel
    command: ["start.sh", "microservices"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
      - mergerfs
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:b6124ab2e45cc332e16398022a411d7e37181f21ff7874835e0180f56a09e82a
    restart: always

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.1.11@sha256:0335a1a22f8c5dd1b697f14f079934f5152eaaa216c09b61e293be285491f8ee
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  nginx:
    container_name: nginx
    image: nginx:latest
    network_mode: host
    volumes:
      - /mnt/media_rw/3d24fb66-314f-48b9-a26f-f91999170865/.ugreen_nas/155924/nginx/html:/usr/share/nginx/html:ro
      - /mnt/media_rw/3d24fb66-314f-48b9-a26f-f91999170865/.ugreen_nas/155924/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - dashy
    restart: always

  dashy:
    container_name: dashy
    image: lissy93/dashy:latest
    environment:
      - NODE_ENV=production
      - UID=0
      - GID=0
    volumes:
      - /mnt/media_rw/3d24fb66-314f-48b9-a26f-f91999170865/.ugreen_nas/155924/dashy/my-conf.yml:/app/public/conf.yml
    network_mode: bridge
    ports:
      - 4000:80
    restart: always

  clash-premium:
    container_name: clash-premium
    image: dreamacro/clash-premium:latest
    volumes:
      - /mnt/media_rw/3d24fb66-314f-48b9-a26f-f91999170865/.ugreen_nas/155924/clash/config.yaml:/root/.config/clash/config.yaml:ro
    network_mode: host
    restart: always

  rathole:
    container_name: rathole
    image: rapiz1/rathole:latest
    entrypoint:
      - ./rathole
    volumes:
      - /mnt/media_rw/3d24fb66-314f-48b9-a26f-f91999170865/.ugreen_nas/155924/rathole/config.toml:/app/config.toml
    network_mode: host
    command:
      - /app/config.toml
    depends_on:
      - jellyfin
      - komga
    restart: always

  mergerfs:
    container_name: mergerfs
    image: ghcr.io/hotio/mergerfs
    init: true
    volumes:
      - /mnt/media_rw/3ADE-8B88:/branch_1
      - /mnt/media_rw/67FC-C44D:/branch_2
      - /mnt/mergerfs/mountpoint:/mountpoint:shared
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse
    command: -o allow_other /branch_1:/branch_2 /mountpoint
    restart: always

volumes:
  pgdata:
  model-cache:
