version: "3.8"

services:
  qbittorrent:
    container_name: qbittorrent
    image: hotio/qbittorrent:latest
    environment:
      - PUID=1559240000
      - PGID=1559240000
      - TZ=Asia/Shanghai
      - WEBUI_PORT=8080
      - UMASK=002
    volumes:
      - /mnt/media_rw/3d24fb66-314f-48b9-a26f-f91999170865/.ugreen_nas/155924/qbittorrent:/config
      - /mnt/mergerfs/mountpoint:/downloads
      - /mnt/media_rw/3d24fb66-314f-48b9-a26f-f91999170865/.ugreen_nas/155924/qbittorrent/tmpdl:/tmpdl
    network_mode: host
    depends_on:
      mergerfs:
        condition: service_healthy

  jellyfin:
    container_name: jellyfin
    image: linuxserver/jellyfin:latest
    environment:
      - PUID=1559240000
      - PGID=1559240000
      - TZ=Asia/Shanghai
      - DOCKER_MODS=docker.io/linuxserver/mods:jellyfin-opencl-intel
      - HTTP_PROXY=http://10.10.10.6:7890
      - HTTPS_PROXY=http://10.10.10.6:7890
    volumes:
      - /mnt/media_rw/3d24fb66-314f-48b9-a26f-f91999170865/.ugreen_nas/155924/jellyfin/custom-files:/custom-cont-init.d:ro
      - /mnt/media_rw/3d24fb66-314f-48b9-a26f-f91999170865/.ugreen_nas/155924/jellyfin/config:/config
      - /mnt/media_rw/3d24fb66-314f-48b9-a26f-f91999170865/.ugreen_nas/155924/jellyfin/fonts:/usr/share/fonts
      - /mnt/mergerfs/mountpoint:/data
    network_mode: host
    devices:
      - /dev/dri:/dev/dri
    depends_on:
      sing-box:
        condition: service_started
      mergerfs:
        condition: service_healthy

  komga:
    container_name: komga
    image: gotson/komga:latest
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /mnt/media_rw/3d24fb66-314f-48b9-a26f-f91999170865/.ugreen_nas/155924/komga/config:/config
      - /mnt/media_rw/3d24fb66-314f-48b9-a26f-f91999170865/.ugreen_nas/155924/komga/tmp:/tmp
      - /mnt/mergerfs/mountpoint/Books:/data
    network_mode: host
    user: "1559240000:1559240000"
    depends_on:
      mergerfs:
        condition: service_healthy

  homeassistant:
    container_name: homeassistant
    image: homeassistant/home-assistant:latest
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /mnt/media_rw/3d24fb66-314f-48b9-a26f-f91999170865/.ugreen_nas/155924/homeassistant/config:/config
    privileged: true
    network_mode: host

  immich-server:
    container_name: immich_server
    image: altran1502/immich-server:${IMMICH_VERSION:-release}
    command: ["start.sh", "immich"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      immich-redis:
        condition: service_started
      immich-postgres:
        condition: service_started

  immich-microservices:
    container_name: immich_microservices
    image: altran1502/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.yml
    #   service: hwaccel
    command: ["start.sh", "microservices"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    depends_on:
      immich-redis:
        condition: service_started
      immich-postgres:
        condition: service_started

  immich-machine-learning:
    container_name: immich_machine_learning
    image: altran1502/immich-machine-learning:${IMMICH_VERSION:-release}
    environment:
      - HTTP_PROXY=http://10.10.10.6:7890
      - HTTPS_PROXY=http://10.10.10.6:7890
    volumes:
      - /mnt/media_rw/3d24fb66-314f-48b9-a26f-f91999170865/.ugreen_nas/155924/immich/cache:/cache
    env_file:
      - .env
    depends_on:
      sing-box:
        condition: service_started
      mergerfs:
        condition: service_healthy

  immich-redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:b6124ab2e45cc332e16398022a411d7e37181f21ff7874835e0180f56a09e82a
    depends_on:
      mergerfs:
        condition: service_healthy

  immich-postgres:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.1.11@sha256:0335a1a22f8c5dd1b697f14f079934f5152eaaa216c09b61e293be285491f8ee
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - /mnt/media_rw/3d24fb66-314f-48b9-a26f-f91999170865/.ugreen_nas/155924/immich/pgdata:/var/lib/postgresql/data
    depends_on:
      mergerfs:
        condition: service_healthy

  nginx:
    container_name: nginx
    image: nginx:latest
    network_mode: host
    volumes:
      - /mnt/media_rw/3d24fb66-314f-48b9-a26f-f91999170865/.ugreen_nas/155924/nginx/html:/usr/share/nginx/html:ro
      - /mnt/media_rw/3d24fb66-314f-48b9-a26f-f91999170865/.ugreen_nas/155924/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      dashy:
        condition: service_started

  dashy:
    container_name: dashy
    image: lissy93/dashy:latest
    environment:
      - NODE_ENV=production
      - UID=1559240000
      - GID=1559240000
    volumes:
      - /mnt/media_rw/3d24fb66-314f-48b9-a26f-f91999170865/.ugreen_nas/155924/dashy/my-conf.yml:/app/public/conf.yml
    network_mode: bridge
    ports:
      - 4000:80

  sing-box:
    container_name: sing-box
    image: ghcr.io/sagernet/sing-box:v1.8.2
    entrypoint: sing-box run -c /root/config.json
    volumes:
      - /mnt/media_rw/3d24fb66-314f-48b9-a26f-f91999170865/.ugreen_nas/155924/sing-box/config.json:/root/config.json
    network_mode: host

  rathole:
    container_name: rathole
    image: rapiz1/rathole:latest
    entrypoint:
      - ./rathole
    volumes:
      - /mnt/media_rw/3d24fb66-314f-48b9-a26f-f91999170865/.ugreen_nas/155924/rathole/config.toml:/app/config.toml
    network_mode: host
    command:
      - /app/config.toml
    depends_on:
      jellyfin:
        condition: service_started
      komga:
        condition: service_started

  mergerfs:
    container_name: mergerfs
    image: hotio/mergerfs:latest
    init: true
    volumes:
      - /mnt/media_rw/3ADE-8B88:/branch_1
      - /mnt/media_rw/67FC-C44D:/branch_2
      - /mnt/mergerfs/mountpoint:/mountpoint:shared
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse
    command: -o cache.files=partial,dropcacheonclose=true,category.create=mfs,allow_other /branch_1:/branch_2 /mountpoint
    healthcheck:
      test: "exit 0"
      interval: 5s

  # icloudpd:
  #   container_name: icloudpd
  #   image: boredazfcuk/icloudpd:latest
  #   volumes:
  #     - /mnt/media_rw/3d24fb66-314f-48b9-a26f-f91999170865/.ugreen_nas/155924/icloudpd/config:/config
  #     - /mnt/media_rw/3d24fb66-314f-48b9-a26f-f91999170865/.ugreen_nas/155924/icloudpd/iCloud:/iCloud
  #   depends_on:
  #     mergerfs:
  #       condition: service_healthy
  #
  # node:
  #   container_name: node
  #   image: node:20-alpine
  #   stdin_open: true
  #   tty: true
  #   volumes:
  #     - /mnt/mergerfs/mountpoint:/mountpoint
  #   depends_on:
  #     sing-box:
  #       condition: service_started
  #     mergerfs:
  #       condition: service_healthy
